### ISSUE TITLE
[FORTINET] add Fortinet to supported Vendors

### ISSUE THREAD

**Issue by anarkia1976** [xmacan/plugin_snver#2]
Hi @xmacan , this plugin is very interesting. Is it possible to add Fortinet Vendor?
thanks a lot

**Comment by xmacan** [comment]
It partially works for fortigate firewalls, because these support Entity MIB:
Organization:
sysObjectID: OID: .1.3.6.1.4.1.12356.101.1.1041
Organization: Fortinet, Inc. (id: 12356)

Entity MIB:
Name: FGT_100E
Description: Fortinet FGT_100E, HW Serial#: FG100ETKxxxxxxx
SW revision: FortiGate-100E v6.2.9,build1234,210601 (GA)
Serial number: FG100ETKxxxxxxx
Manufact. name: Fortinet
Model name: FGT_100E

Vendor specific:
Serial: FG100ETKxxxxxx
Version: v6.2.9,build1234,210601 (GA)

I only have firewalls, so I can't test their other devices. The whole work is about find and add interesting snmp oids to setup.php.

**Comment by anarkia1976** [comment]
HI @xmacan , very good i'm waiting. We have a lot of fortinet machine for test purposing. thanks.

**Comment by xmacan** [comment]
which kind of devices except firewalls?

**Comment by anarkia1976** [comment]
we have, 
fortiadc fortimanager fortianalyzer fortiauthenticator fortimail.
thanks

**Comment by anarkia1976** [comment]
Hi @xmacan,

seems i need to import sql schema after install:
Please import SQL data from file plugins/snver/data/ent.sql
Do you have suggestions?
thanks

**Comment by xmacan** [comment]
It is described in readme.
cd .../plugins/snver/data
mysql -u cacti_user -p cacti_db < ent.sql

It is bigger table, so I decided to import it manually

**Comment by anarkia1976** [comment]
> It is described in readme. cd .../plugins/snver/data mysql -u cacti_user -p cacti_db < ent.sql
> 
> It is bigger table, so I decided to import it manually

In this moment i can't see sql steps into readme file, but it isn't a problem. :)
thanks a lot for your great work as always.

**Comment by xmacan** [comment]
Does fortimail supports EntityMIB? And other devices?

**Comment by anarkia1976** [comment]
yes, it is supported.

**Comment by xmacan** [comment]
So can we close this issue?

**Comment by anarkia1976** [comment]
thanks al lot. closed.
